### ISSUE TITLE
Allow option to run against current directory git repo

### ISSUE THREAD

**Issue by edwardmlyte** [plumming/dx#54]
Something like:
`chilly get prs --here`
or
`chilly get prs .`

**Comment by garethjevans** [comment]
Would you want to run against the repo that is cloned locally, or the fork?  Am just thinking of how to determine what the repo is?

**Comment by garethjevans** [comment]
e.g. if you've cloned `plumming/chilly` to `ed/chilly` and run the command from the fork, what repo would you expect to see?

**Comment by cagiti** [comment]
> e.g. if you've cloned `plumming/chilly` to `ed/chilly` and run the command from the fork, what repo would you expect to see?

how about both?
